/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-26 07:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/icia.semiproject/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/drawAcademy/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1708260482529L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>MyPage</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/mypage.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("   integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"bodyMain\">\r\n");
      out.write("	<img src=\"resources/images/mypage.demitasse.PNG\" class=demitasse>\r\n");
      out.write("    <div class=\"headerMenu\">\r\n");
      out.write("        <button class=\"Home-btn\" onclick=\"location.href='./'\">\r\n");
      out.write("            <img src=\"resources/images/lg.png\" class=\"logo\">\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("        My Page\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"middle-part\">\r\n");
      out.write("        <p>내 정보</p>\r\n");
      out.write("        <div class=\"low-part\">\r\n");
      out.write("            <form action=\"mypage\" method=\"get\">\r\n");
      out.write("                <p>이름 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberDto.m_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <p>이메일 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberDto.m_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <p>전화번호 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberDto.m_phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <p>주소 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberDto.m_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <p>나이 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberDto.m_age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <p>내 수강신청 확인</p>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </form>\r\n");
      out.write("    </div><!-- low-part-->\r\n");
      out.write("  \r\n");
      out.write("     <div class=\"btn-con\">\r\n");
      out.write("        <div class=\"classCancle\">\r\n");
      out.write("            <form action=\"classCancle\" method=\"get\" class=\"cancleBtn\">\r\n");
      out.write("                <button type=\"submit\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    수강신청취소\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"classCancle\">\r\n");
      out.write("            <form action=\"setting\" method=\"get\" class=\"settingBtn\">\r\n");
      out.write("                <button type=\"submit\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    회원정보수정\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("       	 </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"classCancle\">\r\n");
      out.write("            <form action=\"memout\" method=\"get\" class=\"memoutBtn\">\r\n");
      out.write("                <button type=\"submit\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    회원탈퇴\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       	 \r\n");
      out.write("    </div><!-- btn-con -->\r\n");
      out.write("    </div> <!-- bodymain -->\r\n");
      out.write("      \r\n");
      out.write("   </div><!-- middle-part -->\r\n");
      out.write("   <div class=\"headerMenu\">\r\n");
      out.write("         <button class=\"Home-btn\" onclick=\"location.href='./'\">\r\n");
      out.write("            <img src=\"resources/images/lg.png\" class=\"logo\">\r\n");
      out.write("         </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"menu-container\">\r\n");
      out.write("         <img src=\"resources/images/menu.png\" id=\"menuButton\">\r\n");
      out.write("         <div id=\"rectangle\">\r\n");
      out.write("            <br> <br>\r\n");
      out.write("            <button class=\"Home-btn\" onclick=\"location.href='./'\">\r\n");
      out.write("               <p>HOME</p>\r\n");
      out.write("            </button>\r\n");
      out.write("            <br> <br> <br>\r\n");
      out.write("            <button class=\"ABOUT-btn\" onclick=\"location.href='./about'\">\r\n");
      out.write("               <p>ABOUT</p>\r\n");
      out.write("            </button>\r\n");
      out.write("            <br> <br> <br>\r\n");
      out.write("            <button class=\"INSTRUCTORS-btn\"\r\n");
      out.write("               onclick=\"location.href='./instructors'\">\r\n");
      out.write("               <p>INSTRUCTORS</p>\r\n");
      out.write("            </button>\r\n");
      out.write("            <br> <br> <br>\r\n");
      out.write("            <button class=\"CLASS-btn\" onclick=\"location.href='./classpage'\">\r\n");
      out.write("               <p>CLASS</p>\r\n");
      out.write("            </button>\r\n");
      out.write("            <br> <br> <br>\r\n");
      out.write("            <button class=\"CONTACT-btn\" onclick=\"location.href='./contact'\">\r\n");
      out.write("               <p>CONTACT</p>\r\n");
      out.write("            </button>\r\n");
      out.write("            <br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("            <div class=\"smallWord\">\r\n");
      out.write("               <button id=\"loginBtn\" class=\"LOGIN-btn\"\r\n");
      out.write("                  onclick=\"location.href='./login'\">\r\n");
      out.write("                  <small>LOGIN</small>\r\n");
      out.write("               </button>\r\n");
      out.write("               <form id=\"logoutForm\" action=\"logout\" method=\"get\">\r\n");
      out.write("                  <button class=\"LOGIN-btn\" onclick=\"location.href='./'\">\r\n");
      out.write("                     <small>LOGOUT</small>\r\n");
      out.write("                  </button>\r\n");
      out.write("               </form>\r\n");
      out.write("               <button id=\"signupBtn\" class=\"SIGNUP-btn\"\r\n");
      out.write("                  onclick=\"location.href='./signUp'\">\r\n");
      out.write("                  <small>SIGN UP</small>\r\n");
      out.write("               </button>\r\n");
      out.write("               <button id=\"myPage\" class=\"MYPAGE-btn\"\r\n");
      out.write("                  onclick=\"location.href='./mypage'\">\r\n");
      out.write("                  <small>MY PAGE</small>\r\n");
      out.write("               </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br> <br>\r\n");
      out.write("            <div id=\"icon-container2\">\r\n");
      out.write("               <a href=\"https://www.facebook.com\"> <img\r\n");
      out.write("                  src=\"resources/images/facebookIcon.png\" class=\"facebook\">\r\n");
      out.write("               </a> <a href=\"https://www.youtube.com\"> <img\r\n");
      out.write("                  src=\"resources/images/youtubeIcon.png\" class=\"youtube\">\r\n");
      out.write("               </a> <a href=\"https://www.instagram.com\"> <img\r\n");
      out.write("                  src=\"resources/images/instagramIcon.png\" class=\"instagram\">\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"icon-container\">\r\n");
      out.write("         <a href=\"https://www.facebook.com\"> <img\r\n");
      out.write("            src=\"resources/images/facebookIcon.png\" class=\"facebook\">\r\n");
      out.write("         </a> <a href=\"https://www.youtube.com\"> <img\r\n");
      out.write("            src=\"resources/images/youtubeIcon.png\" class=\"youtube\">\r\n");
      out.write("         </a> <a href=\"https://www.instagram.com\"> <img\r\n");
      out.write("            src=\"resources/images/instagramIcon.png\" class=\"instagram\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let msg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("if(msg != \"\"){\r\n");
      out.write("	alert(msg);\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("   var rectangle = document.getElementById('rectangle');\r\n");
      out.write("   var menuButton = document.getElementById('menuButton');\r\n");
      out.write("   var iconContainer = document.getElementById('icon-container');\r\n");
      out.write("   var isRectangleVisible = false; // rectangle의 초기 상태를 정의 - 첫 메뉴 클릭 때 실행되지 않는 현상 해결\r\n");
      out.write("\r\n");
      out.write("   menuButton.addEventListener('click', function() {\r\n");
      out.write("      if (!isRectangleVisible) {\r\n");
      out.write("         rectangle.style.display = 'block';\r\n");
      out.write("         iconContainer.style.display = 'none'; //메뉴 창이 나오면서 iconcontainer 사라지기\r\n");
      out.write("         isRectangleVisible = true; // rectangle이 보이는 상태로 설정\r\n");
      out.write("      } else {\r\n");
      out.write("         rectangle.style.display = 'none';\r\n");
      out.write("         iconContainer.style.display = 'flex';\r\n");
      out.write("         isRectangleVisible = false; // rectangle이 숨겨진 상태로 설정\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write(" \r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("  var loginBtn = document.getElementById(\"loginBtn\");\r\n");
      out.write("  var logoutForm = document.getElementById(\"logoutForm\");\r\n");
      out.write("  var signupBtn = document.getElementById(\"signupBtn\");\r\n");
      out.write("  var myPageBtn = document.getElementById(\"myPage\");\r\n");
      out.write("\r\n");
      out.write("  var loggedInMember = '");
      out.print(session.getAttribute("login"));
      out.write("';\r\n");
      out.write("  \r\n");
      out.write("      console.log(\"세션에 저장된 값: \" + loggedInMember);\r\n");
      out.write("      // 여기서 로그인 여부를 확인하고 그에 따라 버튼을 표시하거나 숨깁니다.\r\n");
      out.write("      var isLoggedIn = loggedInMember !== 'null' && loggedInMember !== '';\r\n");
      out.write("\r\n");
      out.write("      if (isLoggedIn) {\r\n");
      out.write("         loginBtn.style.display = \"none\";\r\n");
      out.write("         logoutForm.style.display = \"block\";\r\n");
      out.write("         signupBtn.style.display = \"none\";\r\n");
      out.write("         myPageBtn.style.display = \"block\";\r\n");
      out.write("      } else {\r\n");
      out.write("         loginBtn.style.display = \"block\";\r\n");
      out.write("         logoutForm.style.display = \"none\";\r\n");
      out.write("         signupBtn.style.display = \"block\";\r\n");
      out.write("         myPageBtn.style.display = \"none\";\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/member/mypage.jsp(38,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cl");
      // /WEB-INF/views/member/mypage.jsp(38,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/mypage.jsp(38,20) '${cList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cl.className}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write(':');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cl.day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cl.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cl.time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
