/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-05 05:02:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.QBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/icia.semiproject/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/drawAcademy/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1709467646910L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>게시물 목록</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/qboard.css\">\n");
      out.write("<!-- jQuery 라이브러리 추가 -->\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\n");
      out.write("	integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script>\n");
      out.write("   $(function() {\n");
      out.write("      let m = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("      if (m != \"\") {\n");
      out.write("         alert(m);\n");
      out.write("      }\n");
      out.write("   });\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<div class=title>FAQ</div>\n");
      out.write("	<header class=\"headerMenu\">\n");
      out.write("		<button class=\"Home-btn\" onclick=\"location.href='./'\">\n");
      out.write("			<img src=\"resources/images/lg.png\" class=\"logo\">\n");
      out.write("		</button>\n");
      out.write("		<div id=\"menu-container\">\n");
      out.write("			<img src=\"resources/images/menu.png\" id=\"menuButton\">\n");
      out.write("			<div id=\"rectangle\">\n");
      out.write("				<br> <br>\n");
      out.write("				<button class=\"Home-btn\" onclick=\"location.href='./'\">\n");
      out.write("					<p>HOME</p>\n");
      out.write("				</button>\n");
      out.write("				<br> <br> <br>\n");
      out.write("				<button class=\"ABOUT-btn\" onclick=\"location.href='./about'\">\n");
      out.write("					<p>ABOUT</p>\n");
      out.write("				</button>\n");
      out.write("				<br> <br> <br>\n");
      out.write("				<button class=\"INSTRUCTORS-btn\"\n");
      out.write("					onclick=\"location.href='./instructors'\">\n");
      out.write("					<p>INSTRUCTORS</p>\n");
      out.write("				</button>\n");
      out.write("				<br> <br> <br>\n");
      out.write("				<button class=\"CLASS-btn\" onclick=\"location.href='./classpage'\">\n");
      out.write("					<p>CLASS</p>\n");
      out.write("				</button>\n");
      out.write("				<br> <br> <br>\n");
      out.write("				<button class=\"CONTACT-btn\" onclick=\"location.href='./qboard'\">\n");
      out.write("					<p>FAQ</p>\n");
      out.write("				</button>\n");
      out.write("				<br> <br> <br> <br> <br> <br> <br>\n");
      out.write("				<div class=\"smallWord\">\n");
      out.write("					<button id=\"loginBtn\" class=\"LOGIN-btn\"\n");
      out.write("						onclick=\"location.href='./login'\">\n");
      out.write("						<small>LOGIN</small>\n");
      out.write("					</button>\n");
      out.write("					<form id=\"logoutForm\" action=\"logout\" method=\"get\">\n");
      out.write("						<button class=\"LOGIN-btn\" onclick=\"location.href='./'\">\n");
      out.write("							<small>LOGOUT</small>\n");
      out.write("						</button>\n");
      out.write("					</form>\n");
      out.write("					<button id=\"signupBtn\" class=\"SIGNUP-btn\"\n");
      out.write("						onclick=\"location.href='./signUp'\">\n");
      out.write("						<small>SIGN UP</small>\n");
      out.write("					</button>\n");
      out.write("					<button id=\"myPage\" class=\"MYPAGE-btn\"\n");
      out.write("						onclick=\"location.href='./mypage'\">\n");
      out.write("						<small>MY PAGE</small>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("				<br> <br>\n");
      out.write("				<div id=\"icon-container2\">\n");
      out.write("					<a href=\"https://www.facebook.com\"> <img\n");
      out.write("						src=\"resources/images/facebookIcon.png\" class=\"facebook\">\n");
      out.write("					</a> <a href=\"https://www.youtube.com\"> <img\n");
      out.write("						src=\"resources/images/youtubeIcon.png\" class=\"youtube\">\n");
      out.write("					</a> <a href=\"https://www.instagram.com\"> <img\n");
      out.write("						src=\"resources/images/instagramIcon.png\" class=\"instagram\">\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"icon-container\">\n");
      out.write("			<a href=\"https://www.facebook.com\"> <img\n");
      out.write("				src=\"resources/images/facebookIcon.png\" class=\"facebook\">\n");
      out.write("			</a> <a href=\"https://www.youtube.com\"> <img\n");
      out.write("				src=\"resources/images/youtubeIcon.png\" class=\"youtube\">\n");
      out.write("			</a> <a href=\"https://www.instagram.com\"> <img\n");
      out.write("				src=\"resources/images/instagramIcon.png\" class=\"instagram\">\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<div class=\"header-title\">\n");
      out.write("	<div class=\"frequent-title\">자주 묻는 질문\n");
      out.write("	<form action=\"searchProc\" method=\"get\">\n");
      out.write("					<input type=\"text\" name=\"searchText\" placeholder=\"게시물검색\">\n");
      out.write("					<div class=btn-con>\n");
      out.write("						<button class=\"searchB\" type=\"submit\">\n");
      out.write("							<span></span> \n");
      out.write("							<span></span> \n");
      out.write("							<span></span> \n");
      out.write("							<span></span> \n");
      out.write("							검색\n");
      out.write("						</button>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"middle-box\">\n");
      out.write("		<div class=\"frequent-question\">\n");
      out.write("			<div class=\"faqCard\">\n");
      out.write("				<div class=\"question\">\n");
      out.write("					Q: 개인 레슨은 가능한가요?\n");
      out.write("					<button class=\"downButton\">+</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"answer\">A: 강사와 조율하면 개인 레슨이 가능합니다.</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"faqCard\">\n");
      out.write("				<div class=\"question\">\n");
      out.write("					Q: 처음 춤을 출 수 있나요?\n");
      out.write("					<button class=\"downButton\">+</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"answer\">A: 네, 누구나 춤을 출 수 있습니다. 본인의 노력에 따라 결과가\n");
      out.write("					달라집니다.</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"faqCard\">\n");
      out.write("				<div class=\"question\">\n");
      out.write("					Q: 수업 별 가격은 어떻게 되나요?\n");
      out.write("					<button class=\"downButton\">+</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"answer\">A: k-pop 25,000원, girlish 30,000원, hip-hop\n");
      out.write("					25,000원입니다.</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- 검색 목록 -->\n");
      out.write("		<div class=\"search\">\n");
      out.write("			<h4 class=\"searchList\">검색 목록</h4>\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!-- 게시물 -->\n");
      out.write("		<div class=\"content-box\">\n");
      out.write("			<div class=\"commentList\">\n");
      out.write("				<div class=\"test1\">\n");
      out.write("					<p class=\"test\">게시물 목록</p>\n");
      out.write("					<button id=\"cklogin\" class= \"searchB\" onclick=\"location.href='./qwrite'\">\n");
      out.write("					<span></span>\n");
      out.write("					<span></span>\n");
      out.write("					<span></span>\n");
      out.write("					<span></span>\n");
      out.write("					질문등록</button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				<!-- 페이지 기능 -->\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"paging-area\">\n");
      out.write("				<div class=\"paging\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	");

	System.out.println("seachResultJSP : " + request.getAttribute("searchResult"));
	
      out.write("\n");
      out.write("</body>\n");
      out.write("<!-- 메뉴 버튼 기능 -->\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("	\n");
      out.write("   var rectangle = document.getElementById('rectangle');\n");
      out.write("   var menuButton = document.getElementById('menuButton');\n");
      out.write("   var iconContainer = document.getElementById('icon-container');\n");
      out.write("   var isRectangleVisible = false; // rectangle의 초기 상태를 정의 - 첫 메뉴 클릭 때 실행되지 않는 현상 해결\n");
      out.write("\n");
      out.write("   menuButton.addEventListener('click', function() {\n");
      out.write("      if (!isRectangleVisible) {\n");
      out.write("         rectangle.style.display = 'block';\n");
      out.write("         iconContainer.style.display = 'none'; //메뉴 창이 나오면서 iconcontainer 사라지기\n");
      out.write("         isRectangleVisible = true; // rectangle이 보이는 상태로 설정\n");
      out.write("      } else {\n");
      out.write("         rectangle.style.display = 'none';\n");
      out.write("         iconContainer.style.display = 'flex';\n");
      out.write("         isRectangleVisible = false; // rectangle이 숨겨진 상태로 설정\n");
      out.write("      }\n");
      out.write("   });\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write(" \n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("  var loginBtn = document.getElementById(\"loginBtn\");\n");
      out.write("  var logoutForm = document.getElementById(\"logoutForm\");\n");
      out.write("  var signupBtn = document.getElementById(\"signupBtn\");\n");
      out.write("  var myPageBtn = document.getElementById(\"myPage\");\n");
      out.write("\n");
      out.write("  var loggedInMember = '");
      out.print(session.getAttribute("login"));
      out.write("';\n");
      out.write("  console.log(\"세션에 저장된 값: \" + loggedInMember);\n");
      out.write("  // 여기서 로그인 여부를 확인하고 그에 따라 버튼을 표시하거나 숨깁니다.\n");
      out.write("  var isLoggedIn = loggedInMember !== 'null' && loggedInMember !== '';\n");
      out.write("\n");
      out.write("  if (isLoggedIn) {\n");
      out.write("    loginBtn.style.display = \"none\";\n");
      out.write("    logoutForm.style.display = \"block\";\n");
      out.write("    signupBtn.style.display = \"none\";\n");
      out.write("    myPageBtn.style.display =\"block\";\n");
      out.write("  } else {\n");
      out.write("    loginBtn.style.display = \"block\";\n");
      out.write("    logoutForm.style.display = \"none\";\n");
      out.write("    signupBtn.style.display= \"block\";\n");
      out.write("    myPageBtn.style.display=\"none\";\n");
      out.write("  }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("   var downButtons = document.querySelectorAll('.downButton');\n");
      out.write("\n");
      out.write("   downButtons.forEach(function(button) {\n");
      out.write("      button.addEventListener('click', function(event) {\n");
      out.write("         var question = event.target.closest('.question');\n");
      out.write("         var answer = question.nextElementSibling;\n");
      out.write("\n");
      out.write("         // 현재 표시 여부를 확인하여 토글\n");
      out.write("         if (answer.style.display === 'block') {\n");
      out.write("            answer.style.display = 'none';\n");
      out.write("            button.textContent = '+';\n");
      out.write("         } else {\n");
      out.write("            answer.style.display = 'block';\n");
      out.write("            button.textContent = '-';\n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("   });\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/QBoard/qboard.jsp(144,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty searchResult}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/QBoard/qboard.jsp(145,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("search");
      // /WEB-INF/views/QBoard/qboard.jsp(145,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/QBoard/qboard.jsp(145,4) '${searchResult}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${searchResult}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					<div class=\"search-item\">\n");
            out.write("						<ul>\n");
            out.write("							<li>\n");
            out.write("							<a href=\"./detail?b_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">제목 :\n");
            out.write("								");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\n");
            out.write("							</li>\n");
            out.write("						</ul>\n");
            out.write("					</div>\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/QBoard/qboard.jsp(171,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty qList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"qboard-item\">\n");
          out.write("						<span class=\"none-content\">등록된 게시물이 없습니다.</span>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/QBoard/qboard.jsp(177,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qList ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/QBoard/qboard.jsp(178,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("qqq");
      // /WEB-INF/views/QBoard/qboard.jsp(178,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/QBoard/qboard.jsp(178,5) '${qList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${qList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						<div class=\"qboard-item\">\n");
            out.write("							<a id=\"qlist\" href=\"./detail?b_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qqq.b_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">제목 :\n");
            out.write("								\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qqq.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" </a>\n");
            out.write("						</div>\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
